server:
  port: 9004

logging:
  level:
    root: info
    org.springframework.web: INFO
    org.springframework.security: INFO


spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: d5e863e1a4ea47e2216f
            client-secret: 18da614dde5e90425708403f0172220028eb63f4












