server:
  port: 9003

spring:
  redis:
    host: 192.168.108.47
    password: 123456
    # 连接超时时间（记得添加单位，Duration）
    timeout: 10000ms
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    # database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0

  cache:
    # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
    type: redis

justauth:
  enabled: true
  type:
    github:
      client-id: a39e409bc9b7dcb49870
      client-secret: 2791ce0653bdb38b8a3e3c689028d48e9d4db400
      redirect-uri: https://localhost:9003/login
    wechat:
      client-id: wxdcb******4ff4
      client-secret: b4e9dc************************a08ed6d
      redirect-uri: http://oauth.xkcoding.com/demo/oauth/wechat/callback
    google:
      client-id: 716******17-6db******vh******ttj320i******userco******t.com
      client-secret: 9IBorn************7-E
      redirect-uri: http://oauth.xkcoding.com/demo/oauth/google/callback
#    ruoyi:
#      client-id: client2
#      client-secret: admin
#      redirect-uri: https://localhost:9002/login
  cache:
    type: redis
    prefix: 'SOCIAL::STATE::'
    timeout: 1h
